### PR TITLE
Data assembly and model prep

### PR DESCRIPTION
**Pull request by jdiaz4302**
# Summary

Adds the `01_process` directory

All code needed to:
* A - Match/organize MN ice observations with TOHA data release drivers (by MN DOW identifier).
* B - Convert ice transition date observations into binary time series and assemble those with the TOHA drivers
* C - Perform further missing data cleaning and partition sequences into train/validation/test (with each partition having mutually exclusive lakes)

# Broader repository structure/design

This project is in a very prototyping/exploratory phase, so the intention is to keep it clean and effective while getting results quickly. As such, there is no canonical configuration file or pipelining/automation. To avoid the extra overhead and implementation of that corresponding best practice, I am attempting to keep all configuration-like settings/values at the top of the notebook in an obvious cell block. 

I am following our general practice of phased directories (e.g., `01_process`) and input (`in`), output (`out`), and code (`src`) directories. Notebooks are used to easily provide dataframe previewing, plot inspection, and print statements without executing the code again. To maintain a sense of flow, within directories I will follow an `A_FirstNotebook.ipynb`, `B_SecondNotebook.ipynb`, ... naming pattern.

# Requested review

May include but not limited to:

* General bug identification
* Improved documentation of configuration values or notetaking that may benefit later transition to pipelining
* Input on higher level data prep or modeling decisions

### CODE REVIEW

**Review by AndyMcAliley — APPROVED** [review]
This looks great! I have comments and questions, but no mandatory changes to recommend.

I agree that using notebooks is a good way to move forward quickly. As an aside, Jeff suggested [Jupytext](https://jupytext.readthedocs.io/en/latest/index.html) for sharing notebook code through repositories, although it doesn't include cell outputs (for better - less repo storage, and for worse - folks have to run the code themselves to inspect dataframes, see plots, etc). I haven't adopted it, though.

The configuration cells at the top of each notebook are a good way to track settings and especially input and output files. I think they'll make it easy to implement a pipeline later.

## Approach

I have a couple of thoughts about implementation choices.

If I understand correctly, lakes with no PGDL estimates are kept out of the training set in Notebook A. Later, though, PGDL estimates are removed from the training set. Could you expand the training set by keeping lakes with no PGDL estimates?

I'm not clear on how PB estimates or PGDL estimates will be used - as additional inputs or for pretraining.

Every sequence begins in summer, when there is no ice. Will it affect training for every sequence to start and end with warm temperatures and no ice? Maybe it gives the model a better chance to learn how cold temperatures early in the freeze affect the time when the last lake ice thaws. I'm just wondering how this would compare to training using sequences that start at a random time of year, and/or sequences that last longer than a year.

## Code review

I couldn't run the code since I don't have `MN_ice/ice_duration_summarized.csv`. Here are some code-specific comments:

### A_MergeIceObsWithDrivers.ipynb

Cell 5: assert is a keyword rather than a function, so it's better to include a space after it, as in `assert 1+2==3`.

Is it possible for one NHDHR to correspond to multiple DOWs? Looks like there's a check for that in cell after "Create a new data set for easily referencing between the observation and drivers", though I can't say if that check suffices to answer the question. Maybe another assertion, or raise an Exception?

`cur_df['nhdhr'].unique().item()` will probably fail if there are multiple DOWs for one NHDHR.

### B_ModelSequenceCreation

Displaying the `ice_dur` dataframe in cell 3 helps - thank you!

Weird about needing `engine='python'`. Sounds like a nasty pandas bug.

You could consider saving NHDHR ids in the npz files. I don't know if that would matter or not, since DOW IDs are already in the metadata.

`vars` in cell 11 is a non-specific keyword - you could consider `features`.

### C_TrainTestSplits

Looks good!

**Comment by AndyMcAliley** [comment]
Regarding "Improved documentation of configuration values": if you think someone besides you might be converting this into a pipeline at some later point, you could divide that configuration notebook cell into three sections: one for settings, one for file inputs, and one for file outputs.

**Comment by jdiaz4302** [comment]
Thanks, Andy! I'll make sure to share that ice data before the next PR.

## Replies

> If I understand correctly, lakes with no PGDL estimates are kept out of the training set in Notebook A. Later, though, PGDL estimates are removed from the training set. Could you expand the training set by keeping lakes with no PGDL estimates?

Lakes that are missing PGDL estimates are handled by the `try` and `except` calls; I'm still gathering all the _available_ data for those lakes, just not the PGDL estimates, so the end result is the same when PGDL estimates are excised. 

> I'm not clear on how PB estimates or PGDL estimates will be used - as additional inputs or for pretraining.

Currently, only as inputs (will be shown in the next PR). I'll look at the promise of pretraining though.

> Every sequence begins in summer, when there is no ice. Will it affect training for every sequence to start and end with warm temperatures and no ice? Maybe it gives the model a better chance to learn how cold temperatures early in the freeze affect the time when the last lake ice thaws. I'm just wondering how this would compare to training using sequences that start at a random time of year, and/or sequences that last longer than a year.

Yeah, that's an interesting point and, at a minimum, sequences that start at different times will be a good evaluation check. The start/end points of the sequences were chosen to match the start/end points of the yearly ice observations (set by the collaborators) which are organized by "winter year" which start at 7/1/N-1 and end at 6/30/N

> Is it possible for one NHDHR to correspond to multiple DOWs? 

Yes. Here, one NHDHR can be matched to multiple DOWs, but (that check shows) that multiple NHDHRs cannot be matched to one DOW. 

This is actually demonstrated in the data set preview:

multiplenhdhr

> cur_df['nhdhr'].unique().item() will probably fail if there are multiple DOWs for one NHDHR.

The resulting behavior is that multiple targets (ice observations sorted by DOW) are created for the same driver data (sorted by NHDHR). Put another way, the identical driver data creates x1 and x2, but differently identified data create y1 and y2, leading to x1 == x2 but y1 =/= y2.

Matching needed to be done by one the identifiers, and it seems better to be "loyal" to the prediction target. Alternatively, using NHDHR (which occasionally encompasses multiple DOWs) or being loyal to the driver data would mean that we would need to identify one of the DOWs as the true lake. Quick/qualitative inspection showed that the ice observations for multiple DOWs matched to the same NHDHR could have nontrivial differences in ice dates. **I think I will open an issue to flesh this out/document it more.**

> Weird about needing engine='python'. Sounds like a nasty pandas bug.

Agreed, it confused me and wasted my time for a little bit. I think it may be resolved in newer versions, but **my environment, which I'll document soon**, is configured around other libraries/dependencies too.

> You could consider saving NHDHR ids in the npz files. I don't know if that would matter or not, since DOW IDs are already in the metadata.

Yeah, this is in-line with the potential issue/documentation idea above.

> vars in cell 11 is a non-specific keyword - you could consider features.

Agreed

**Comment by jdiaz4302** [comment]
One additional change I'm going to make prior to merging is changing the ice sequences to be made with maximum ice onset data rather than minimum ice onset data. Jordan discussed this before, and our collaborator, Gretchen, proposed maximum. In 92.5% of cases the difference is less than one day, but in the cases where they are different Gretchen argued that latest ice formation would be more useful to predict

**Comment by AndyMcAliley** [comment]
> 
> > Is it possible for one NHDHR to correspond to multiple DOWs?
> 
> Yes. Here, one NHDHR can be matched to multiple DOWs, but (that check shows) that multiple NHDHRs cannot be matched to one DOW.

Oops - I meant to ask if multiple NHDHR can match the same DOW. Glad that you're checking if they do or not.

> cur_df['nhdhr'].unique().item() will probably fail if there are multiple DOWs for one NHDHR.

Here again, I meant if there are multiple NHDHRs for one DOW.

**Comment by jdiaz4302** [comment]
Ah, okay. Regarding that, I went ahead and added additional, very explicit checks that occur in cell blocks 6-8 of notebook A.

Also,
* Assertations fixed
* Configuration header elaborated into inputs, values, and outputs
* `vars` -> `features`
* Using `max_ice_on` instead of `min_ice_on`

**Pull request merged**
